# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62e9beacc483ccb9d43afc0a70cce98313c84a2636507d2207ddba37ca4ec68beab3efa6caaadc29329d43ba96b97c3993ade2f3c098f3a682d1ffbbe2a80603

test:
  secret_key_base: a86f26381cc9fb9afd733c2aecab974012aed6b19d48793811c4d283aa3b69fe489153870e448031bd63f4d1e2f7e75a45a67c6f8ee5245a96b795bc1e97aee1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
